apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-notification-service-config
  namespace: flet-montrg
  labels:
    app: alert-notification-service
data:
  APP_NAME: "Alert Notification Service"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "[\"*\"]"
  DEBUG: "false"
  ALERT_SERVICE_URL: "http://alert-service:80"
  ALERT_SUBSCRIPTION_SERVICE_URL: "http://alert-subscription-service:80"
