apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flet-montrg

resources:
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- hpa.yaml
- network-policy.yaml

commonLabels:
  app: alert-notification-service
  version: v1.0.0

images:
- name: alert-notification-service
  newTag: latest
