apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-subscription-service-config
  namespace: flet-montrg
  labels:
    app: alert-subscription-service
data:
  APP_NAME: "Alert Subscription Service"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "[\"*\"]"
  DEBUG: "false"
  LOCATION_SERVICE_URL: "http://location-service:80"
