apiVersion: v1
kind: Service
metadata:
  name: alert-subscription-service
  namespace: flet-montrg
  labels:
    app: alert-subscription-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30008
    protocol: TCP
  - name: metrics
    port: 8000
    targetPort: 8000
    nodePort: 30237
    protocol: TCP
  selector:
    app: alert-subscription-service
