apiVersion: v1
kind: ConfigMap
metadata:
  name: sensor-threshold-mapping-service-config
  namespace: flet-montrg
  labels:
    app: sensor-threshold-mapping-service
data:
  APP_NAME: "Sensor Threshold Mapping Service"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "[\"*\"]"
  DEBUG: "false"
  THRESHOLDS_SERVICE_URL: "http://thresholds-service:80"
  LOCATION_SERVICE_URL: "http://location-service:80"
