apiVersion: v1
kind: Secret
metadata:
  name: sensor-threshold-mapping-service-secret
  namespace: flet-montrg
  labels:
    app: sensor-threshold-mapping-service
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vcG9zdGdyZXM6cG9zdGdyZXNAMTcyLjE4LjAuODo1NDMyL2hx   # base64 encoded
