apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-service-config
  namespace: flet-montrg
  labels:
    app: alert-service
data:
  APP_NAME: "Alert Service"
  APP_VERSION: "1.0.0"
  ENVIRONMENT: "production"
  HOST: "0.0.0.0"
  PORT: "8000"
  LOG_LEVEL: "INFO"
  CORS_ORIGINS: "[\"*\"]"
  DEBUG: "false"
  THRESHOLDS_SERVICE_URL: "http://thresholds-service:80"
  LOCATION_SERVICE_URL: "http://location-service:80"
  ALERT_SUBSCRIPTION_SERVICE_URL: "http://alert-subscription-service:80"
  ALERT_NOTIFICATION_SERVICE_URL: "http://alert-notification-service:80"
  SENSOR_THRESHOLD_MAPPING_SERVICE_URL: "http://sensor-threshold-mapping-service:80"
